/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as FriendsFriendIdRouteImport } from './routes/friends.$friendId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/$friendId',
  path: '/$friendId',
  getParentRoute: () => FriendsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/transactions': typeof TransactionsRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/transactions': typeof TransactionsRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/transactions': typeof TransactionsRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/friends' | '/insights' | '/transactions' | '/friends/$friendId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/friends' | '/insights' | '/transactions' | '/friends/$friendId'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/insights'
    | '/transactions'
    | '/friends/$friendId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$friendId': {
      id: '/friends/$friendId'
      path: '/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof FriendsRoute
    }
  }
}

interface FriendsRouteChildren {
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
}

const FriendsRouteChildren: FriendsRouteChildren = {
  FriendsFriendIdRoute: FriendsFriendIdRoute,
}

const FriendsRouteWithChildren =
  FriendsRoute._addFileChildren(FriendsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRouteWithChildren,
  InsightsRoute: InsightsRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
